### ISSUE TITLE
Bug loading a single plugin (validator, parser, etc)

### ISSUE THREAD

**Issue by EHER** [codelicia/xulieta#59]
Using the configuration:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xulieta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/codelicia/xulieta/xulieta.xsd">
    <validator>Codelicia\XulietaJson\JsonValidator</validator>
    <validator>Codelicia\XulietaJson\JsonValidator</validator>
</xulieta>
```
validators will be an array and with the configuration:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xulieta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/codelicia/xulieta/xulieta.xsd">
    <validator>Codelicia\XulietaJson\JsonValidator</validator>
</xulieta>
```
validators will be a string.

```
Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidTypeException: Invalid type for path "xulieta.validator". Expected "array", but got "string" in /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/ArrayNode.php:254
Stack trace:
#0 /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/BaseNode.php(566): Symfony\Component\Config\Definition\ArrayNode->validateType('Codelicia\\Xulie...')
#1 /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/BaseNode.php(409): Symfony\Component\Config\Definition\BaseNode->doValidateType('Codelicia\\Xulie...')
#2 /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/ArrayNode.php(285): Symfony\Component\Config\Definition\BaseNode->normalize('Codelicia\\Xulie...')
#3 /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/BaseNode.php(412): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#4 /home/eher/git/git in /home/eher/git/github.com/codelicia/xulieta-json/vendor/symfony/config/Definition/ArrayNode.php on line 254
```

**Comment by EHER** [comment]
I may have found the right configuration to always get an array.
